org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2

# Mod Properties
version=1.0.0
maven_group=com.dowwrey

# Dependencies
fabric_api_version=0.162.0+26.3
